name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install LLVM 18 toolchain
        run: |
          sudo apt-get update -y
          sudo apt-get install -y llvm-18 llvm-18-tools clang-18 lld-18
          echo "LLVM_SYS_180_PREFIX=/usr/lib/llvm-18" >> $GITHUB_ENV
          echo "/usr/lib/llvm-18/bin" >> $GITHUB_PATH
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: WYRMC_CLANG=/usr/lib/llvm-18/bin/clang-18 cargo test --workspace
